#!/bin/zsh
set -eu; base=${0:a:h}; source $base/common; sayhi $0

# args: foldername langs
folder=$1; langs=($*[2,-1]); show folder langs

for subfolder in $1/*.lproj; do
	code=${${${subfolder%.lproj}//_/-}:t:l} # strip all parts bu language code, lowercase, hyphen separators
  if string_in_array $code $langs; then
    print "keeping ${subfolder:t}"	
  else
    print "deleting ${subfolder:t}"
	  rm -rf $subfolder
  fi
done

saybye $0
