#!/bin/zsh
set -eu; base=${0:a:h}/..; source $base/common; cd_info

interactive=yes
while getopts 'q' c; do
  case $c in
    q) interactive=no ;;
  esac
done

# cd to our temp dir 
cd_info
load_info app_path app_zip bundle_id edition channel version build

# is this is something we would like to publish to web
if [[ $edition != $edition_sa || ( $channel != $channel_beta && $channel != $channel_prod ) ]]; then
  print "Not notarizing edition: $edition, channel $channel"; exit
fi

if [[ $interactive == yes ]]; then
  echo; askuser "Ready to go. Send this for notarization?"
fi

# upload
echo "uploading to Apple's notarization service..."
json=$(altool --notarize-app --asc-provider NicholasMoore1324598518 --file $app_zip --primary-bundle-id $bundle_id)
echo $json | jq

# save uuid
uuid=$(param $json notarization-upload RequestUUID); show uuid
save_info uuid

