#!/bin/zsh
set -eu; base=${0:a:h}/..; source $base/common; cd_info

# cd to our temp dir 
cd_info
load_info app_path app_zip bundle_id 
echo; askuser "Ready to go. Send this for notarization?"

# upload
echo "uploading to Apple's notarization service..."
json=$(altool --notarize-app --asc-provider NicholasMoore1324598518 --file $app_zip --primary-bundle-id $bundle_id)
echo $json | jq

# save uuid
uuid=$(param $json notarization-upload RequestUUID); show uuid
save_info uuid

